### PR TITLE
Add Auctionator price source

### PR DESCRIPTION
**Pull request by b-morgan**
Please accept this minor enhancement to add Auctionator as a price source. I did not change the version number in the .toc file.

### CODE REVIEW

**Review by Noshei — CHANGES_REQUESTED** [review]
This looks good, but there is one bit that I would want changed.  Specifically this line:
`options[10] = "Auctionator"`
it should use a unique key to not cause any conflicts, as this value is what gets sets stored in the saved variables.  I'd say change it to 20, to give room if other options need to be added for ReCrystalize in the future and it should be fine.

**Comment by b-morgan** [comment]
I wasn't sure about that but 20 sounds good to me. Does line 281 in Utilities need "and GT.db.profile.General.tsmPrice == 20" added as well?

**Review by b-morgan — COMMENTED** [review]
Changed from 10 to 20. Does line 281 in Utilities need to add "and GT.db.profile.General.tsmPrice == 20"?

**Comment by Noshei** [comment]
> Changed from 10 to 20. Does line 281 in Utilities need to add "and GT.db.profile.General.tsmPrice == 20"?

yeah, that condition would need to be added.

**Comment by Noshei** [comment]
Also, that if statement should go above the TSM one.  As the TSM one acts as a sort of fall back.

**Comment by b-morgan** [comment]
I believe my novice Git skills have corrected everything.

**Comment by Noshei** [comment]
looks good to me.  I'll get this merged and tested.

**Pull request merged**
